services:
  - type: web
    name: weather-web
    env: python
    region: oregon  # tumhare paas region option, select karo
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn weather_project.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: weather_project.settings
      - key: PYTHON_VERSION
        value: "3.13"
